### ISSUE TITLE
No module named 'netmiko.ssh_exception' as of netmiko>=4.1.1

### ISSUE THREAD

**Issue by angely-dev** [napalm-automation-community/napalm-ce#21]
To reproduce:

```py
from napalm import get_network_driver
driver = get_network_driver('ce')
device = driver(hostname='blabla', username='hello', password='there')
device.open()
print(device.get_facts())
```

Stack trace with `netmiko==4.1.1` (and above):

```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    driver = get_network_driver('ce')
  File "venv/lib/python3.10/site-packages/napalm/base/__init__.py", line 97, in get_network_driver
    raise e
  File "venv/lib/python3.10/site-packages/napalm/base/__init__.py", line 88, in get_network_driver
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "venv/lib/python3.10/site-packages/napalm_ce/__init__.py", line 16, in <module>
    from napalm_ce.ce import CEDriver  # noqa
  File "venv/lib/python3.10/site-packages/napalm_ce/ce.py", line 34, in <module>
    from netmiko.ssh_exception import NetMikoTimeoutException
ModuleNotFoundError: No module named 'netmiko.ssh_exception'
```

Line: https://github.com/napalm-automation-community/napalm-ce/blob/v0.2.0/napalm_ce/ce.py#L34
It works with `netmiko==4.1.0`.

Possible fix: https://github.com/ktbyers/netmiko/issues/3032#issuecomment-1317615560

**Comment by TasselYUE** [comment]
please use translation tools to translate my words.
进入到napalm-ce的包中，定位到napalm/ce.py这个文件

![Image](https://github.com/user-attachments/assets/5df7b662-dfd7-4d72-a3d6-00e7ab26e6f0)

将报错的from netmiko.ssh_exceptions 改为 netmiko.exceptions。
就不会报错了
