### ISSUE TITLE
napalm.base.exceptions.ModuleImportError: No class inheriting "napalm.base.base.NetworkDriver" found in "napalm.ce"

### ISSUE THREAD

**Issue by quanghong** [napalm-automation-community/napalm-ce#24]
Hi,

I have import issue
```
from napalm import get_network_driver

driver = get_network_driver("ce")
print(driver)
```

`raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: No class inheriting "napalm.base.base.NetworkDriver" found in "napalm.ce".
`

Versions:
python: 3.8.18
napalm: 4.1.0
napalm-ce: 0.2.0

**Comment by quanghong** [comment]
The module is imported successfully when i execute python command. But i have issue when i execute by python file.

ubuntu@ubuntu:~$ python3.8 /home/ubuntu/TEST_script/network-monitor/test/napalm_ce.py
```
Traceback (most recent call last):
  File "/home/ubuntu/TEST_script/network-monitor/test/napalm_ce.py", line 3, in <module>
    driver = get_network_driver("ce")
  File "/home/ubuntu/.local/lib/python3.8/site-packages/napalm/base/__init__.py", line 88, in get_network_driver
    module = importlib.import_module(module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/TEST_script/network-monitor/test/napalm_ce.py", line 3, in <module>
    driver = get_network_driver("ce")
  File "/home/ubuntu/.local/lib/python3.8/site-packages/napalm/base/__init__.py", line 110, in get_network_driver
    raise ModuleImportError(
napalm.base.exceptions.ModuleImportError: No class inheriting "napalm.base.base.NetworkDriver" found in "napalm.ce".
```
ubuntu@ubuntu:~$ python3.8
```
Python 3.8.18 (default, Mar 15 2024, 15:27:46) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from napalm import get_network_driver
>>> driver = get_network_driver("ce")
>>> print(driver)
<class 'napalm_ce.ce.CEDriver'>
>>> import importlib
>>> importlib
<module 'importlib' from '/usr/local/lib/python3.8/importlib/__init__.py'>
```
